"""Load the authored question bank into the database.

The seed is run repeatedly — on a fresh environment, after a content edit, and in CI — so it has
to be idempotent in a way that preserves history. Questions are matched on ``source_key`` rather
than on primary key, because the primary key is generated by the database and the content file
has no way to know it.

Change detection is by content hash rather than by field comparison. A version is created *only*
when the authored content actually differs from what is published, so re-running the seed on
unchanged content leaves version history alone. Without that, every deploy would publish a new
identical version and the history that exists to explain past grades would become noise.
"""

import hashlib
import json
from pathlib import Path
from typing import Any

from core import logger
from core.constants.enums import QuestionStatus, QuestionVersionStatus
from core.cruds.category_crud import CRUDCategory
from core.cruds.question_crud import CRUDQuestion, CRUDQuestionVersion
from core.models.question_model import QuestionVersion
from core.services.questions.rubric_service import RubricValidator

logging = logger(__name__)

DEFAULT_SEED_PATH = Path(__file__).resolve().parents[3] / "seeds" / "questions.json"
CONTENT_FIELDS = ("prompt", "ideal_answer", "expected_concepts", "common_mistakes", "rubric")
TAXONOMY_FIELDS = ("category_slug", "subcategory", "difficulty")


class QuestionSeeder:
    """Loads authored question content into the bank, idempotently."""

    def __init__(self, *, seed_path: Path | None = None) -> None:
        """
        Initialise the seeder with a content file and the layers it writes through.

        Args:
            seed_path: Path to the authored JSON file. Defaults to ``backend/seeds/questions.json``.
        """
        self.seed_path = seed_path or DEFAULT_SEED_PATH
        self.CRUDQuestion = CRUDQuestion()
        self.CRUDQuestionVersion = CRUDQuestionVersion()
        self.CRUDCategory = CRUDCategory()
        self.RubricValidator = RubricValidator()

    async def run(self, *, activate: bool = True, dry_run: bool = False) -> dict[str, Any]:
        """
        Load every question in the content file, creating or updating as needed.

        Validation runs against every entry before anything is written. A content file with a
        broken rubric fails the whole run rather than seeding a partially valid bank, because a
        half-seeded bank is harder to reason about than an unseeded one.

        Args:
            activate: Whether to set successfully published questions ACTIVE.
            dry_run: Validate and report without writing anything.

        Returns:
            dict[str, Any]: Counts of created, updated, unchanged and failed entries, plus any
            validation errors found.

        Raises:
            FileNotFoundError: If the content file does not exist.
            ValueError: If any entry fails rubric validation.
        """
        logging.info("Executing QuestionSeeder.run")
        entries = self._load()
        self._validate_all(entries)

        summary: dict[str, Any] = {
            "total": len(entries),
            "created": 0,
            "updated": 0,
            "unchanged": 0,
            "activated": 0,
            "dry_run": dry_run,
        }
        if dry_run:
            logging.info(f"Dry run: {len(entries)} entries validated, nothing written")
            return summary

        await self._require_categories(entries)

        for entry in entries:
            outcome = await self._apply(entry=entry, activate=activate)
            summary[outcome["result"]] += 1
            if outcome["activated"]:
                summary["activated"] += 1

        logging.info(
            f"Question seed complete: {summary['created']} created, "
            f"{summary['updated']} updated, {summary['unchanged']} unchanged"
        )
        return summary

    def _load(self) -> list[dict[str, Any]]:
        """
        Read and parse the authored content file.

        Returns:
            list[dict[str, Any]]: The question entries.

        Raises:
            FileNotFoundError: If the file does not exist.
            ValueError: If an entry has no source key, or two entries share one.
        """
        if not self.seed_path.exists():
            raise FileNotFoundError(f"Question seed file not found: {self.seed_path}")

        payload = json.loads(self.seed_path.read_text())
        entries: list[dict[str, Any]] = payload.get("questions", [])

        keys = [str(entry["source_key"]) for entry in entries if entry.get("source_key")]
        if len(keys) != len(entries):
            raise ValueError("Every seed entry needs a source_key")
        duplicates = {key for key in keys if keys.count(key) > 1}
        if duplicates:
            # A duplicate key would make the upsert ambiguous: the second entry would silently
            # overwrite the first, and the bank would be one question short with no error.
            raise ValueError(f"Duplicate source keys in the seed file: {sorted(duplicates)}")
        return entries

    def _validate_all(self, entries: list[dict[str, Any]]) -> None:
        """
        Validate every entry's rubric before any write happens.

        Args:
            entries: Parsed content entries.

        Raises:
            ValueError: If any entry is not publishable, listing every failure at once.
        """
        failures: list[str] = []
        for entry in entries:
            result = self.RubricValidator.validate(version=self._content(entry))
            if not result.is_valid:
                failures.append(f"{entry['source_key']}: {'; '.join(result.errors)}")

        if failures:
            logging.error(f"Question seed failed validation for {len(failures)} entries")
            raise ValueError("Seed content failed rubric validation:\n" + "\n".join(failures))

    async def _require_categories(self, entries: list[dict[str, Any]]) -> None:
        """
        Verify every category referenced by the content file exists.

        Checked up front rather than per row, so a typo in one slug fails immediately instead of
        after half the bank has been written.

        Args:
            entries: Parsed content entries.

        Raises:
            ValueError: If any referenced category is missing.
        """
        known = {category.slug for category in await self.CRUDCategory.list_all()}
        referenced = {entry["category_slug"] for entry in entries}
        missing = sorted(referenced - known)
        if missing:
            raise ValueError(f"Seed references categories that do not exist: {missing}")

    async def _apply(self, *, entry: dict[str, Any], activate: bool) -> dict[str, Any]:
        """
        Create or update one question and its published content.

        Args:
            entry: One parsed content entry.
            activate: Whether to set the question ACTIVE once it has a published version.

        Returns:
            dict[str, Any]: The outcome for this entry and whether it was activated.
        """
        source_key = entry["source_key"]
        taxonomy = {field: entry.get(field) for field in TAXONOMY_FIELDS}
        content = self._content(entry)

        question = await self.CRUDQuestion.get_by_source_key(source_key=source_key)
        if question is None:
            question = await self.CRUDQuestion.create(
                obj_in={
                    **taxonomy,
                    "source_key": source_key,
                    "status": QuestionStatus.DRAFT,
                }
            )
            await self._publish(question_id=question.id, content=content)
            activated = await self._maybe_activate(question_id=question.id, activate=activate)
            logging.info(f"Seeded new question {source_key}")
            return {"result": "created", "activated": activated}

        changed_taxonomy = {
            field: value for field, value in taxonomy.items() if getattr(question, field) != value
        }
        if changed_taxonomy:
            await self.CRUDQuestion.update(question_id=question.id, obj_in=changed_taxonomy)

        published = await self.CRUDQuestionVersion.get_published(question_id=question.id)
        content_changed = published is None or self._hash(content) != self._hash(
            self._version_content(published)
        )

        if content_changed:
            await self._publish(question_id=question.id, content=content)
            activated = await self._maybe_activate(question_id=question.id, activate=activate)
            logging.info(f"Published new version of {source_key}")
            return {"result": "updated", "activated": activated}

        activated = await self._maybe_activate(question_id=question.id, activate=activate)
        result = "updated" if changed_taxonomy else "unchanged"
        return {"result": result, "activated": activated}

    async def _publish(self, *, question_id: Any, content: dict[str, Any]) -> None:
        """
        Create a version from authored content and publish it.

        Args:
            question_id: Owning question.
            content: Validated version content.
        """
        version = await self.CRUDQuestionVersion.create(
            obj_in={**content, "question_id": question_id}
        )
        await self.CRUDQuestionVersion.publish(version_id=version.id)

    async def _maybe_activate(self, *, question_id: Any, activate: bool) -> bool:
        """
        Set a question ACTIVE when it has a published version and activation is requested.

        Mirrors the guard the admin API enforces: a question only becomes selectable once
        something can actually grade it.

        Args:
            question_id: Question to activate.
            activate: Whether activation was requested at all.

        Returns:
            bool: True when the question's status was changed to ACTIVE.
        """
        if not activate:
            return False

        question = await self.CRUDQuestion.get_with_versions(question_id=question_id)
        if question is None or question.status == QuestionStatus.ACTIVE:
            return False
        if not any(
            version.status == QuestionVersionStatus.PUBLISHED for version in question.versions
        ):
            return False

        await self.CRUDQuestion.update(
            question_id=question_id, obj_in={"status": QuestionStatus.ACTIVE}
        )
        return True

    @staticmethod
    def _content(entry: dict[str, Any]) -> dict[str, Any]:
        """
        Extract the version content fields from a seed entry.

        Args:
            entry: One parsed content entry.

        Returns:
            dict[str, Any]: Content fields, with list and object fields defaulted.
        """
        return {
            "prompt": entry.get("prompt", ""),
            "ideal_answer": entry.get("ideal_answer", ""),
            "expected_concepts": entry.get("expected_concepts", []),
            "common_mistakes": entry.get("common_mistakes", []),
            "rubric": entry.get("rubric", {}),
        }

    @staticmethod
    def _version_content(version: QuestionVersion) -> dict[str, Any]:
        """
        Extract a stored version's content in the same shape as an authored entry.

        Args:
            version: The stored version.

        Returns:
            dict[str, Any]: Content fields ready to hash against authored content.
        """
        return {field: getattr(version, field) for field in CONTENT_FIELDS}

    @staticmethod
    def _hash(content: dict[str, Any]) -> str:
        """
        Produce a stable fingerprint of version content.

        Sorted keys make the hash independent of field order, so reordering the JSON file does
        not look like a content change and does not create a spurious version.

        Args:
            content: Version content fields.

        Returns:
            str: Hex digest of the canonical JSON form.
        """
        canonical = json.dumps(content, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode()).hexdigest()
