/**
 * The glossary term bank.
 *
 * Categories mirror the eight question categories the product actually teaches, so a term a
 * student meets in a question is filed where they would look for it. Terms that belonged to no
 * question category (duration, convexity, alpha) were removed — the glossary is a companion to
 * the bank, not a general finance dictionary.
 *
 * `aliases` are the other surface forms the same idea appears in, and they are what makes the
 * inline glossary useful: a prompt says "discounted cash flow", "levered", or "D&A" far more
 * often than it says the canonical heading.
 */

export interface GlossaryTerm {
  id: string;
  term: string;
  definition: string;
  category: GlossaryCategory;
  /** Other spellings, acronyms and inflections that should resolve to this term inline. */
  aliases?: string[];
  related?: string[];
  explanation?: string;
}

/** The eight product categories, in the order the diagnostic ramps through them. */
export const GLOSSARY_CATEGORIES = [
  'Accounting',
  'Enterprise & Equity Value',
  'Valuation',
  'DCF',
  'M&A / Merger Modelling',
  'LBO & Private Equity',
  'Financial Statement Analysis',
  'Markets, Deals & Judgment',
] as const;

export type GlossaryCategory = (typeof GLOSSARY_CATEGORIES)[number];

export const glossaryTerms: GlossaryTerm[] = [
  // ---------------------------------------------------------------- Accounting
  {
    id: 'three-statements',
    term: 'Three Financial Statements',
    aliases: ['three statements', 'financial statements', 'three financial statements'],
    definition:
      'The income statement, balance sheet and cash flow statement — the three linked reports that describe a company’s performance, position and cash.',
    category: 'Accounting',
    related: ['income-statement', 'balance-sheet', 'cash-flow-statement'],
    explanation:
      'They are linked, not independent: net income flows from the income statement into the top of the cash flow statement and into retained earnings on the balance sheet, and the closing cash balance from the cash flow statement is the cash line on the balance sheet.',
  },
  {
    id: 'income-statement',
    term: 'Income Statement',
    aliases: ['P&L', 'profit and loss statement'],
    definition:
      'The statement of revenue, costs and profit over a period, ending in net income.',
    category: 'Accounting',
    related: ['net-income', 'gross-margin', 'ebitda'],
  },
  {
    id: 'balance-sheet',
    term: 'Balance Sheet',
    definition:
      'A snapshot at a point in time of what a company owns, what it owes, and the residual belonging to shareholders.',
    category: 'Accounting',
    related: ['working-capital', 'goodwill'],
    explanation:
      'Assets must equal liabilities plus shareholders’ equity. When an interviewer asks you to walk through a change, the balance sheet balancing is the check that you did the other two statements correctly.',
  },
  {
    id: 'cash-flow-statement',
    term: 'Cash Flow Statement',
    definition:
      'The reconciliation from net income to the actual change in cash, split into operating, investing and financing activity.',
    category: 'Accounting',
    related: ['cash-flow-from-operations', 'capex', 'net-income'],
  },
  {
    id: 'net-income',
    term: 'Net Income',
    aliases: ['earnings', 'bottom line'],
    definition:
      'Profit after every expense, including interest and tax — the bottom line of the income statement.',
    category: 'Accounting',
    related: ['income-statement', 'equity-value', 'accretion-dilution'],
  },
  {
    id: 'cash-flow-from-operations',
    term: 'Cash Flow from Operations',
    aliases: ['operating cash flow', 'cash flow from operating activities'],
    definition:
      'Cash generated by the core business, starting from net income and adjusting for non-cash charges and changes in working capital.',
    category: 'Accounting',
    related: ['net-income', 'working-capital', 'depreciation-amortisation'],
    explanation:
      'Net income rising while operating cash flow falls is the classic quality-of-earnings warning: profit is being recognised faster than cash is being collected.',
  },
  {
    id: 'depreciation-amortisation',
    term: 'Depreciation & Amortisation',
    aliases: ['depreciation and amortisation', 'D&A', 'depreciation', 'amortisation', 'amortization'],
    definition:
      'The non-cash expense that spreads the cost of a long-lived asset across the years it is used.',
    category: 'Accounting',
    related: ['ebitda', 'cash-flow-from-operations', 'capex'],
    explanation:
      'Because it is non-cash, it reduces reported profit and tax but is added back on the cash flow statement. That tax shield is why an increase in depreciation raises operating cash flow even as net income falls.',
  },
  {
    id: 'deferred-revenue',
    term: 'Deferred Revenue',
    aliases: ['unearned revenue'],
    definition:
      'Cash collected for a product or service not yet delivered. It is a liability until the obligation is met.',
    category: 'Accounting',
    related: ['working-capital', 'balance-sheet'],
    explanation:
      'For subscription businesses it is a forward-looking signal: growing deferred revenue means bookings are outpacing recognised revenue, and a decline often precedes a revenue slowdown.',
  },
  {
    id: 'write-down',
    term: 'Write-Down',
    aliases: ['writedown', 'write down', 'writes down', 'impairment'],
    definition:
      'Reducing the carrying value of an asset on the balance sheet when it is no longer worth what the books say.',
    category: 'Accounting',
    related: ['goodwill', 'balance-sheet'],
    explanation:
      'A write-down is non-cash, so the cash effect is only the tax saving. Watch the double-entry: the asset falls by the full amount, retained earnings fall by the after-tax amount, and cash rises by the tax shield.',
  },
  {
    id: 'working-capital',
    term: 'Working Capital',
    aliases: ['net working capital', 'NWC', 'changes in working capital'],
    definition:
      'Current operating assets minus current operating liabilities — the cash tied up in running the business day to day.',
    category: 'Accounting',
    related: ['cash-conversion-cycle', 'cash-flow-from-operations', 'free-cash-flow'],
  },
  {
    id: 'capex',
    term: 'Capital Expenditure',
    aliases: ['CapEx', 'capital expenditures', 'capital spending'],
    definition:
      'Cash spent acquiring or upgrading long-lived assets. It appears in investing activities, not as an expense.',
    category: 'Accounting',
    related: ['depreciation-amortisation', 'free-cash-flow'],
  },

  // ------------------------------------------------- Enterprise & Equity Value
  {
    id: 'enterprise-value',
    term: 'Enterprise Value',
    aliases: ['EV', 'TEV', 'total enterprise value'],
    definition:
      'The value of a company’s core operations, independent of how it is financed: equity value plus net debt and other claims.',
    category: 'Enterprise & Equity Value',
    related: ['equity-value', 'net-debt', 'ebitda'],
    explanation:
      'It answers "what are the operations worth", which is why it pairs with capital-structure-neutral metrics such as EBITDA. Raising debt and holding the proceeds in cash leaves it unchanged — debt up, cash up, net debt flat.',
  },
  {
    id: 'equity-value',
    term: 'Equity Value',
    aliases: ['market capitalisation', 'market capitalization', 'market cap'],
    definition:
      'The value of the shares themselves: enterprise value less net debt and other non-equity claims.',
    category: 'Enterprise & Equity Value',
    related: ['enterprise-value', 'net-debt', 'net-income'],
  },
  {
    id: 'net-debt',
    term: 'Net Debt',
    definition: 'Total debt less cash and cash equivalents.',
    category: 'Enterprise & Equity Value',
    related: ['enterprise-value', 'leverage'],
    explanation:
      'Cash is netted because an acquirer takes the company’s cash with it and can use it to repay debt immediately. A company with more cash than debt has negative net debt, and can trade at an enterprise value below its equity value.',
  },
  {
    id: 'ebitda',
    term: 'EBITDA',
    aliases: ['earnings before interest, taxes, depreciation and amortisation'],
    definition:
      'Earnings before interest, taxes, depreciation and amortisation — a rough proxy for operating cash generation before financing and accounting choices.',
    category: 'Enterprise & Equity Value',
    related: ['enterprise-value', 'depreciation-amortisation', 'leverage'],
    explanation:
      'It sits above interest, so it belongs to all capital providers and pairs with enterprise value. Pairing it with equity value — or pairing net income with enterprise value — mixes claims and gives a meaningless multiple.',
  },
  {
    id: 'diluted-shares',
    term: 'Diluted Shares Outstanding',
    aliases: ['diluted shares', 'fully diluted shares', 'diluted share count'],
    definition:
      'The share count including options, warrants and convertibles that are in the money today.',
    category: 'Enterprise & Equity Value',
    related: ['treasury-stock-method', 'equity-value'],
    explanation:
      'Basic shares understate what a buyer actually has to pay for. Anything in the money will convert in a sale, so it is a real claim on the equity.',
  },
  {
    id: 'treasury-stock-method',
    term: 'Treasury Stock Method',
    aliases: ['TSM'],
    definition:
      'The convention for counting in-the-money options: assume they are exercised and the proceeds are used to buy back shares at the current price.',
    category: 'Enterprise & Equity Value',
    related: ['diluted-shares'],
    explanation:
      'Net new shares are therefore the option count less the shares repurchased with the strike proceeds — not the full option count.',
  },

  // ----------------------------------------------------------------- Valuation
  {
    id: 'trading-comparables',
    term: 'Trading Comparables',
    aliases: ['comparable companies', 'trading comps', 'comps', 'comparable company analysis'],
    definition:
      'Valuing a company against the multiples of similar public companies trading today.',
    category: 'Valuation',
    related: ['precedent-transactions', 'ebitda', 'enterprise-value'],
    explanation:
      'It reflects what the market pays right now, for a minority stake, with no control premium. Two companies at identical EBITDA and different multiples usually differ in growth, margin, capital intensity or risk — the gap is the analysis, not an error.',
  },
  {
    id: 'precedent-transactions',
    term: 'Precedent Transactions',
    aliases: ['precedent transaction', 'transaction comparables', 'deal comps'],
    definition:
      'Valuing a company against the multiples actually paid in past acquisitions of similar businesses.',
    category: 'Valuation',
    related: ['trading-comparables', 'control-premium', 'synergies'],
    explanation:
      'Prices paid include a control premium and expected synergies, so they usually sit above trading comps. Their weakness is age: a deal struck in a different rate or credit environment says little about today.',
  },
  {
    id: 'control-premium',
    term: 'Control Premium',
    definition:
      'The amount an acquirer pays above the market price to obtain control of a company.',
    category: 'Valuation',
    related: ['precedent-transactions', 'synergies'],
  },
  {
    id: 'multiple',
    term: 'Multiple',
    aliases: ['valuation multiple', 'trading multiple'],
    definition:
      'A ratio of value to a financial metric — EV/EBITDA, P/E — used to compare companies of different sizes.',
    category: 'Valuation',
    related: ['ebitda', 'enterprise-value', 'trading-comparables'],
  },

  // ----------------------------------------------------------------------- DCF
  {
    id: 'dcf',
    term: 'DCF',
    aliases: ['discounted cash flow', 'discounted cash flow analysis'],
    definition:
      'A valuation built from a company’s own projected cash flows, discounted back to today at the cost of capital.',
    category: 'DCF',
    related: ['wacc', 'terminal-value', 'free-cash-flow'],
    explanation:
      'It is the only intrinsic method on the list — it values the business on what it will produce rather than on what the market is currently paying. That makes it powerful and fragile: the answer moves sharply with assumptions you choose yourself.',
  },
  {
    id: 'wacc',
    term: 'WACC',
    aliases: ['weighted average cost of capital', 'cost of capital', 'discount rate'],
    definition:
      'The blended after-tax return a company must earn to satisfy all its capital providers, weighted by the market value of each.',
    category: 'DCF',
    related: ['cost-of-equity', 'cost-of-debt', 'capm', 'dcf'],
    explanation:
      'It is the discount rate for unlevered free cash flow because those cash flows belong to debt and equity holders alike. Weights are market value, not book value, because that is what the capital is worth today.',
  },
  {
    id: 'cost-of-debt',
    term: 'Cost of Debt',
    aliases: ['after-tax cost of debt', 'pre-tax cost of debt'],
    definition:
      'The rate a company pays on its borrowings, used after tax in WACC.',
    category: 'DCF',
    related: ['wacc', 'leverage'],
    explanation:
      'After tax, because interest is tax-deductible: a 10% coupon at a 25% tax rate costs the company 7.5%. Using the pre-tax rate double-counts the tax shield if the cash flows are already unlevered.',
  },
  {
    id: 'cost-of-equity',
    term: 'Cost of Equity',
    definition:
      'The return equity investors require for holding the shares, usually estimated with CAPM.',
    category: 'DCF',
    related: ['capm', 'beta', 'wacc'],
  },
  {
    id: 'capm',
    term: 'CAPM',
    aliases: ['capital asset pricing model'],
    definition:
      'Capital Asset Pricing Model: cost of equity equals the risk-free rate plus beta times the equity risk premium.',
    category: 'DCF',
    related: ['beta', 'cost-of-equity', 'wacc'],
  },
  {
    id: 'beta',
    term: 'Beta',
    aliases: ['levered beta', 'unlevered beta'],
    definition:
      'How much a stock moves relative to the market as a whole — its systematic, undiversifiable risk.',
    category: 'DCF',
    related: ['capm', 'cost-of-equity'],
    explanation:
      'For a private company or a new segment, take peers’ levered betas, unlever each at its own capital structure, take the median, and relever at the target’s structure.',
  },
  {
    id: 'free-cash-flow',
    term: 'Free Cash Flow',
    aliases: ['FCF', 'unlevered free cash flow', 'levered free cash flow'],
    definition:
      'Cash left after the business funds its own operations and capital spending — what is genuinely available to capital providers.',
    category: 'DCF',
    related: ['dcf', 'capex', 'working-capital'],
    explanation:
      'Unlevered free cash flow is before interest and is discounted at WACC to give enterprise value. Levered free cash flow is after interest and is discounted at the cost of equity to give equity value. Mixing the two is the most common DCF error.',
  },
  {
    id: 'terminal-value',
    term: 'Terminal Value',
    definition:
      'The value of the business beyond the explicit forecast period, where cash flows can no longer be projected individually.',
    category: 'DCF',
    related: ['dcf', 'wacc', 'multiple'],
    explanation:
      'Usually calculated by perpetuity growth or by an exit multiple, and cross-checked against the other. It commonly makes up 60–80% of a DCF; far above that, the model is really a statement about the terminal assumption rather than about the forecast.',
  },
  {
    id: 'mid-year-convention',
    term: 'Mid-Year Convention',
    definition:
      'Discounting each year’s cash flow as if it arrived mid-year rather than at year end.',
    category: 'DCF',
    related: ['dcf', 'wacc'],
    explanation:
      'Cash actually arrives throughout the year, so year-end discounting understates value. The adjustment is worth roughly half a year of discounting — a few percent at typical discount rates.',
  },

  // ------------------------------------------------------ M&A / Merger Modelling
  {
    id: 'accretion-dilution',
    term: 'Accretion / Dilution',
    aliases: ['accretive', 'dilutive', 'accretion', 'dilution'],
    definition:
      'Whether a deal raises or lowers the acquirer’s earnings per share once the transaction is included.',
    category: 'M&A / Merger Modelling',
    related: ['net-income', 'synergies', 'purchase-accounting'],
    explanation:
      'Broadly, paying with cheaper currency than the target’s earnings yield is accretive. It is an arithmetic outcome, not a verdict: a deal can be accretive and value-destroying if the acquirer overpaid, and dilutive but excellent if the asset compounds.',
  },
  {
    id: 'purchase-accounting',
    term: 'Purchase Accounting',
    aliases: ['purchase price allocation', 'PPA'],
    definition:
      'The rules for recording an acquisition: the target’s assets and liabilities are written to fair value and the excess purchase price becomes goodwill.',
    category: 'M&A / Merger Modelling',
    related: ['goodwill', 'write-down'],
  },
  {
    id: 'goodwill',
    term: 'Goodwill',
    definition:
      'The premium paid over the fair value of a target’s identifiable net assets, recorded as an intangible asset.',
    category: 'M&A / Merger Modelling',
    related: ['purchase-accounting', 'write-down'],
    explanation:
      'It is not amortised but is tested for impairment. A large goodwill write-down is a public admission that an acquisition did not deliver.',
  },
  {
    id: 'synergies',
    term: 'Synergies',
    aliases: ['synergy', 'cost synergies', 'revenue synergies'],
    definition:
      'Value created by combining two companies that neither could produce alone — cost savings or additional revenue.',
    category: 'M&A / Merger Modelling',
    related: ['accretion-dilution', 'control-premium'],
    explanation:
      'Cost synergies are more credible than revenue synergies because they are inside management’s control. The real question is not their size but how much of them the acquirer already handed over in the price.',
  },
  {
    id: 'strategic-buyer',
    term: 'Strategic Buyer',
    aliases: ['strategic acquirer', 'strategic'],
    definition:
      'An operating company acquiring another business it can integrate, as opposed to a financial sponsor.',
    category: 'M&A / Merger Modelling',
    related: ['sponsor', 'synergies', 'ipo'],
    explanation:
      'A strategic can usually pay more, because it can underwrite synergies a financial buyer cannot.',
  },

  // ------------------------------------------------------ LBO & Private Equity
  {
    id: 'lbo',
    term: 'LBO',
    aliases: ['leveraged buyout'],
    definition:
      'Acquiring a company using a large amount of borrowed money, repaid out of the company’s own cash flow.',
    category: 'LBO & Private Equity',
    related: ['sponsor', 'leverage', 'irr', 'money-multiple'],
    explanation:
      'A good candidate has stable, predictable cash flow, modest capital needs, a defensible position and a credible exit. Returns come from three places: debt paydown, EBITDA growth and multiple expansion.',
  },
  {
    id: 'sponsor',
    term: 'Sponsor',
    aliases: ['financial sponsor', 'private equity firm'],
    definition:
      'A private equity firm acquiring companies with a mix of fund equity and debt, aiming to exit within a set horizon.',
    category: 'LBO & Private Equity',
    related: ['lbo', 'irr', 'strategic-buyer'],
  },
  {
    id: 'irr',
    term: 'IRR',
    aliases: ['internal rate of return'],
    definition:
      'The annualised return that sets the present value of an investment’s cash flows to zero.',
    category: 'LBO & Private Equity',
    related: ['money-multiple', 'lbo'],
    explanation:
      'It is time-sensitive, so a fast, small win can beat a slow, large one. That is exactly why it is quoted alongside the money multiple rather than instead of it.',
  },
  {
    id: 'money-multiple',
    term: 'Money Multiple',
    aliases: ['MOIC', 'multiple of invested capital', 'cash-on-cash'],
    definition:
      'Total cash returned divided by cash invested, ignoring how long it took.',
    category: 'LBO & Private Equity',
    related: ['irr', 'lbo'],
    explanation:
      'It measures how much money was made; IRR measures how fast. A fund can need one for its headline and the other for its LPs.',
  },
  {
    id: 'capital-structure',
    term: 'Capital Structure',
    definition: 'The mix of debt and equity used to finance a company.',
    category: 'LBO & Private Equity',
    related: ['tranche', 'leverage', 'net-debt'],
  },
  {
    id: 'tranche',
    term: 'Tranche',
    aliases: ['tranches', 'debt tranche'],
    definition:
      'One layer of a debt structure, with its own seniority, pricing and terms.',
    category: 'LBO & Private Equity',
    related: ['capital-structure', 'leverage'],
    explanation:
      'Sponsors use several rather than one because each layer prices its own risk: cheap senior debt takes the safest claim, and more expensive junior capital is only paid for the leverage senior lenders will not provide.',
  },
  {
    id: 'leverage',
    term: 'Leverage',
    aliases: ['levered', 'over-levered', 'leverage ratio', 'gearing'],
    definition:
      'The amount of debt in a capital structure, usually quoted as a multiple of EBITDA.',
    category: 'LBO & Private Equity',
    related: ['net-debt', 'ebitda', 'capital-structure'],
    explanation:
      'Whether a company is over-levered is not a single number: it depends on cash flow stability, covenant headroom, interest coverage and the maturity wall, not on the debt/EBITDA multiple alone.',
  },

  // ---------------------------------------------- Financial Statement Analysis
  {
    id: 'cash-conversion-cycle',
    term: 'Cash Conversion Cycle',
    aliases: ['CCC'],
    definition:
      'How many days pass between paying for inventory and collecting cash from the customer.',
    category: 'Financial Statement Analysis',
    related: ['working-capital', 'cash-flow-from-operations'],
    explanation:
      'A negative cycle means customers pay before suppliers do, so growth funds itself — the structural advantage behind supermarkets and subscription businesses.',
  },
  {
    id: 'gross-margin',
    term: 'Gross Margin',
    definition:
      'Revenue less cost of goods sold, as a percentage of revenue — what is left to cover everything else.',
    category: 'Financial Statement Analysis',
    related: ['income-statement', 'basis-point'],
  },
  {
    id: 'roic',
    term: 'ROIC',
    aliases: ['return on invested capital'],
    definition:
      'After-tax operating profit divided by the capital invested in the business.',
    category: 'Financial Statement Analysis',
    related: ['wacc', 'free-cash-flow'],
    explanation:
      'Growth only creates value when ROIC exceeds WACC; below it, growth destroys value. Its limitations are accounting ones — book capital understates intangible-heavy businesses and overstates ones carrying old goodwill.',
  },
  {
    id: 'basis-point',
    term: 'Basis Point',
    aliases: ['basis points', 'bps'],
    definition: 'One hundredth of a percentage point. 100 basis points is 1%.',
    category: 'Financial Statement Analysis',
    related: ['gross-margin'],
  },

  // ------------------------------------------- Markets, Deals & Judgment
  {
    id: 'ipo',
    term: 'IPO',
    aliases: ['initial public offering', 'going public'],
    definition:
      'A company’s first sale of shares to public investors.',
    category: 'Markets, Deals & Judgment',
    related: ['strategic-buyer', 'sponsor', 'equity-value'],
    explanation:
      'For an owner deciding how to exit, it is the route that gives liquidity over time rather than at once, keeps them in the seat, and exposes the outcome to the market window.',
  },
  {
    id: 'risk-free-rate',
    term: 'Risk-Free Rate',
    definition:
      'The yield on a government bond of comparable duration, used as the base of the cost of equity.',
    category: 'Markets, Deals & Judgment',
    related: ['capm', 'wacc'],
    explanation:
      'When it rises, every discount rate rises with it. That is the channel through which a 200 basis point move in rates cools M&A and LBO activity: debt costs more, leverage available falls, and buyers must underwrite lower entry multiples.',
  },
];
