"""Question bank: stable question identity and versioned grading content.

The split is the most important schema decision in the product. ``questions`` holds identity and
taxonomy, which may be edited freely. ``question_versions`` holds everything the grader reads —
prompt, ideal answer, expected concepts, common mistakes, rubric — and is never updated in place
once published. An attempt records the exact version it was graded against, so editing a rubric
can never retroactively change the meaning of a past grade.
"""

import uuid
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.constants.enums import QuestionStatus, QuestionVersionStatus, in_check
from core.database.base import Base, CreatedAtMixin, TimestampMixin, UUIDPrimaryKeyMixin

MIN_DIFFICULTY = 1
MAX_DIFFICULTY = 5


class Question(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Stable identity and taxonomy for a question, independent of its graded content."""

    __tablename__ = "questions"
    __table_args__ = (
        CheckConstraint(in_check("status", QuestionStatus), name="ck_questions_status"),
        CheckConstraint(
            f"difficulty BETWEEN {MIN_DIFFICULTY} AND {MAX_DIFFICULTY}",
            name="ck_questions_difficulty_range",
        ),
        # Session composition always filters to active questions first, then narrows by category
        # and difficulty. A partial index keeps draft and retired rows out of the structure the
        # hot selection path scans, and stays small as the retired pool grows.
        Index(
            "ix_questions_active_selection",
            "category_slug",
            "difficulty",
            postgresql_where=text("status = 'active'"),
        ),
    )

    # Stable handle for authored content. The primary key is generated by the database, so
    # without this a re-run of the content seed would insert a second copy of every question
    # rather than updating the ones already there.
    source_key: Mapped[str | None] = mapped_column(Text, unique=True)
    category_slug: Mapped[str] = mapped_column(
        ForeignKey("categories.slug", ondelete="RESTRICT"), nullable=False
    )
    subcategory: Mapped[str | None] = mapped_column(Text)
    difficulty: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=QuestionStatus.DRAFT)

    versions: Mapped[list["QuestionVersion"]] = relationship(
        back_populates="question", cascade="all, delete-orphan"
    )


class QuestionVersion(Base, UUIDPrimaryKeyMixin, CreatedAtMixin):
    """An immutable snapshot of a question's prompt and grading rubric.

    Carries no ``updated_at``: a published version is never modified. Changing a rubric creates a
    new version and supersedes the previous one.
    """

    __tablename__ = "question_versions"
    __table_args__ = (
        UniqueConstraint("question_id", "version", name="uq_question_versions_question_version"),
        CheckConstraint(
            in_check("status", QuestionVersionStatus), name="ck_question_versions_status"
        ),
        CheckConstraint("version > 0", name="ck_question_versions_version_positive"),
        # At most one published version per question, enforced by the database. Two published
        # versions would make "which rubric grades this question now" ambiguous, and the answer
        # would vary by query plan.
        Index(
            "uq_question_versions_one_published",
            "question_id",
            unique=True,
            postgresql_where=text("status = 'published'"),
        ),
        # Rubric completeness is a database invariant, not only an admin-form validation. A
        # published version missing its prompt, ideal answer, or expected concepts would silently
        # degrade every grade produced from it.
        CheckConstraint(
            "status <> 'published' OR ("
            " length(btrim(prompt)) > 0"
            " AND length(btrim(ideal_answer)) > 0"
            " AND jsonb_typeof(expected_concepts) = 'array'"
            " AND jsonb_array_length(expected_concepts) > 0"
            ")",
            name="ck_question_versions_published_is_complete",
        ),
        CheckConstraint(
            "jsonb_typeof(expected_concepts) = 'array' AND jsonb_typeof(common_mistakes) = 'array'",
            name="ck_question_versions_json_shapes",
        ),
        Index("ix_question_versions_created_by", "created_by"),
    )

    question_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("questions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    prompt: Mapped[str] = mapped_column(Text, nullable=False)

    # --- Grading-sensitive. These must never appear in a pre-submission API response. ---
    ideal_answer: Mapped[str] = mapped_column(Text, nullable=False)
    expected_concepts: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    common_mistakes: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    rubric: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    # ------------------------------------------------------------------------------------

    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=QuestionVersionStatus.DRAFT
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )

    question: Mapped[Question] = relationship(back_populates="versions")
