"""add question source key

Gives authored content a stable handle that survives re-seeding. Question primary keys are
generated by the database, so a content file has no way to say "this is the same question I
described last time" without one — and re-running the seed would duplicate the whole bank.

Revision ID: a1c4e9f20b31
Revises: 17748c07d87b
Create Date: 2026-09-04 06:10:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1c4e9f20b31"
down_revision: str | None = "17748c07d87b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the nullable, unique source key to questions."""
    op.add_column("questions", sa.Column("source_key", sa.Text(), nullable=True))
    # Unique rather than a plain index: two questions claiming one source key would make the
    # seed's upsert ambiguous, and it would pick a row by query plan.
    op.create_unique_constraint("uq_questions_source_key", "questions", ["source_key"])


def downgrade() -> None:
    """Remove the source key."""
    op.drop_constraint("uq_questions_source_key", "questions", type_="unique")
    op.drop_column("questions", "source_key")
