"""initial schema

Revision ID: ddcf577347e2
Revises:
Create Date: 2026-09-03 16:53:44.016190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ddcf577347e2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("display_order > 0", name="ck_categories_display_order_positive"),
        sa.CheckConstraint("slug = lower(slug)", name="ck_categories_slug_lowercase"),
        sa.PrimaryKeyConstraint("slug"),
        sa.UniqueConstraint("display_order"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("google_sub", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name="ck_users_status"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.CheckConstraint(
            "password_hash IS NOT NULL OR google_sub IS NOT NULL", name="ck_users_has_auth_method"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_sub"),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("school", sa.Text(), nullable=True),
        sa.Column("graduation_year", sa.SmallInteger(), nullable=True),
        sa.Column("target_role", sa.Text(), nullable=True),
        sa.Column(
            "recruiting_consent", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("recruiting_consent_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "marketing_emails_opt_in", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_role IS NULL OR target_role IN ('ib', 'pe', 'both')",
            name="ck_profiles_target_role",
        ),
        sa.CheckConstraint(
            "graduation_year IS NULL OR graduation_year BETWEEN 1950 AND 2100",
            name="ck_profiles_graduation_year_range",
        ),
        sa.CheckConstraint(
            "recruiting_consent IS FALSE OR recruiting_consent_updated_at IS NOT NULL",
            name="ck_profiles_consent_has_timestamp",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "ix_profiles_recruiting_consent", "profiles", ["recruiting_consent"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("category_slug", sa.Text(), nullable=False),
        sa.Column("subcategory", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('draft', 'active', 'retired')", name="ck_questions_status"),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name="ck_questions_difficulty_range"),
        sa.ForeignKeyConstraint(["category_slug"], ["categories.slug"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_questions_active_selection",
        "questions",
        ["category_slug", "difficulty"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="in_progress", nullable=False),
        sa.Column("question_count", sa.SmallInteger(), nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "selection_rationale",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'in_progress') = (finished_at IS NULL)",
            name="ck_sessions_finished_at_matches_status",
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'abandoned')", name="ck_sessions_status"
        ),
        sa.CheckConstraint("type IN ('diagnostic', 'practice')", name="ck_sessions_type"),
        sa.CheckConstraint("question_count > 0", name="ck_sessions_question_count_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sessions_user_in_progress",
        "sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.create_index(
        "ix_sessions_user_started",
        "sessions",
        ["user_id", "started_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "skill_scores",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category_slug", sa.Text(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("previous_score", sa.SmallInteger(), nullable=True),
        sa.Column("evidence_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("evidence_count > 0", name="ck_skill_scores_has_evidence"),
        sa.CheckConstraint(
            "previous_score IS NULL OR previous_score BETWEEN 0 AND 100",
            name="ck_skill_scores_previous_score_range",
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_skill_scores_score_range"),
        sa.ForeignKeyConstraint(["category_slug"], ["categories.slug"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_slug", name="uq_skill_scores_user_category"),
    )
    op.create_index("ix_skill_scores_category", "skill_scores", ["category_slug"], unique=False)
    op.create_index(
        "ix_skill_scores_user_score", "skill_scores", ["user_id", "score"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), server_default="stripe", nullable=False),
        sa.Column("provider_customer_id", sa.Text(), nullable=True),
        sa.Column("provider_subscription_id", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "plan IN ('free', 'pro_monthly', 'season_pass')", name="ck_subscriptions_plan"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'trialing', 'past_due', 'canceled', 'incomplete', 'expired')",
            name="ck_subscriptions_status",
        ),
        sa.CheckConstraint(
            "current_period_end IS NULL OR current_period_start IS NULL OR current_period_end > current_period_start",
            name="ck_subscriptions_period_ordered",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_subscription_id", name="uq_subscriptions_provider_id"),
    )
    op.create_index(
        "ix_subscriptions_customer", "subscriptions", ["provider_customer_id"], unique=False
    )
    op.create_index("ix_subscriptions_user", "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "entitlements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement", sa.Text(), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("source_event_id", sa.Text(), nullable=True),
        sa.Column("source_subscription_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entitlement IN ('pro', 'season_pass')", name="ck_entitlements_entitlement"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')", name="ck_entitlements_status"
        ),
        sa.CheckConstraint(
            "active_until IS NULL OR active_until > active_from",
            name="ck_entitlements_window_ordered",
        ),
        sa.ForeignKeyConstraint(
            ["source_subscription_id"], ["subscriptions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entitlements_source_event", "entitlements", ["source_event_id"], unique=False
    )
    op.create_index(
        "ix_entitlements_subscription", "entitlements", ["source_subscription_id"], unique=False
    )
    op.create_index(
        "ix_entitlements_user_active",
        "entitlements",
        ["user_id", "active_until"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "question_versions",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("ideal_answer", sa.Text(), nullable=False),
        sa.Column(
            "expected_concepts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "rubric",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(expected_concepts) = 'array' AND jsonb_typeof(common_mistakes) = 'array'",
            name="ck_question_versions_json_shapes",
        ),
        sa.CheckConstraint(
            "status <> 'published' OR ( length(btrim(prompt)) > 0 AND length(btrim(ideal_answer)) > 0 AND jsonb_typeof(expected_concepts) = 'array' AND jsonb_array_length(expected_concepts) > 0)",
            name="ck_question_versions_published_is_complete",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'superseded')", name="ck_question_versions_status"
        ),
        sa.CheckConstraint("version > 0", name="ck_question_versions_version_positive"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "version", name="uq_question_versions_question_version"),
    )
    op.create_index(
        "ix_question_versions_created_by", "question_versions", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_question_versions_question_id"), "question_versions", ["question_id"], unique=False
    )
    op.create_index(
        "uq_question_versions_one_published",
        "question_versions",
        ["question_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "attempts",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("grading_status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("band", sa.Text(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("concepts_hit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("concepts_missed", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mistake_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "band IS NULL OR band IN ('strong', 'developing', 'needs_work')",
            name="ck_attempts_band",
        ),
        sa.CheckConstraint(
            "grading_status <> 'graded' OR (score IS NOT NULL AND band IS NOT NULL AND graded_at IS NOT NULL)",
            name="ck_attempts_graded_has_result",
        ),
        sa.CheckConstraint(
            "grading_status IN ('pending', 'grading', 'graded', 'failed')",
            name="ck_attempts_grading_status",
        ),
        sa.CheckConstraint(
            "grading_status NOT IN ('pending', 'grading', 'failed') OR (score IS NULL AND band IS NULL)",
            name="ck_attempts_ungraded_has_no_score",
        ),
        sa.CheckConstraint(
            "char_length(answer) BETWEEN 1 AND 2000", name="ck_attempts_answer_length"
        ),
        sa.CheckConstraint(
            "score IS NULL OR score BETWEEN 0 AND 100", name="ck_attempts_score_range"
        ),
        sa.CheckConstraint(
            "time_taken_seconds IS NULL OR time_taken_seconds >= 0",
            name="ck_attempts_time_taken_non_negative",
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["question_version_id"], ["question_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "question_id", name="uq_attempts_session_question"),
    )
    op.create_index(
        "ix_attempts_question_version", "attempts", ["question_version_id"], unique=False
    )
    op.create_index("ix_attempts_session", "attempts", ["session_id"], unique=False)
    op.create_index(
        "ix_attempts_unresolved_grading",
        "attempts",
        ["submitted_at"],
        unique=False,
        postgresql_where=sa.text("grading_status IN ('pending', 'grading', 'failed')"),
    )
    op.create_index(
        "ix_attempts_user_question_submitted",
        "attempts",
        ["user_id", "question_id", "submitted_at"],
        unique=False,
    )
    op.create_index(
        "ix_attempts_user_submitted", "attempts", ["user_id", "submitted_at"], unique=False
    )
    op.create_table(
        "session_questions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_session_questions_position_non_negative"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["question_version_id"], ["question_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "position", name="uq_session_questions_position"),
        sa.UniqueConstraint("session_id", "question_id", name="uq_session_questions_question"),
    )
    op.create_index(
        "ix_session_questions_question", "session_questions", ["question_id"], unique=False
    )
    op.create_index(
        "ix_session_questions_version", "session_questions", ["question_version_id"], unique=False
    )
    op.create_table(
        "grade_events",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_request_id", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation_status", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('valid', 'invalid_schema', 'invalid_values', 'provider_error', 'timeout')",
            name="ck_grade_events_validation_status",
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0", name="ck_grade_events_input_tokens"
        ),
        sa.CheckConstraint("latency_ms IS NULL OR latency_ms >= 0", name="ck_grade_events_latency"),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="ck_grade_events_output_tokens"
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_grade_events_attempt_created",
        "grade_events",
        ["attempt_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_grade_events_created", "grade_events", ["created_at"], unique=False)
    op.create_index(
        "ix_grade_events_failures",
        "grade_events",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("validation_status <> 'valid'"),
    )
    op.create_table(
        "grade_flags",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('resolved', 'rejected')) = (resolved_at IS NOT NULL)",
            name="ck_grade_flags_resolved_at_matches_status",
        ),
        sa.CheckConstraint(
            "reason IN ('score_too_low', 'score_too_high', 'wrong_concepts', 'unclear_feedback', 'other')",
            name="ck_grade_flags_reason",
        ),
        sa.CheckConstraint(
            "status IN ('open', 'reviewing', 'resolved', 'rejected')", name="ck_grade_flags_status"
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "user_id", name="uq_grade_flags_attempt_user"),
    )
    op.create_index(
        "ix_grade_flags_open",
        "grade_flags",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('open', 'reviewing')"),
    )
    op.create_index("ix_grade_flags_reviewer", "grade_flags", ["reviewer_id"], unique=False)
    op.create_index("ix_grade_flags_user", "grade_flags", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_grade_flags_user", table_name="grade_flags")
    op.drop_index("ix_grade_flags_reviewer", table_name="grade_flags")
    op.drop_index(
        "ix_grade_flags_open",
        table_name="grade_flags",
        postgresql_where=sa.text("status IN ('open', 'reviewing')"),
    )
    op.drop_table("grade_flags")
    op.drop_index(
        "ix_grade_events_failures",
        table_name="grade_events",
        postgresql_where=sa.text("validation_status <> 'valid'"),
    )
    op.drop_index("ix_grade_events_created", table_name="grade_events")
    op.drop_index("ix_grade_events_attempt_created", table_name="grade_events")
    op.drop_table("grade_events")
    op.drop_index("ix_session_questions_version", table_name="session_questions")
    op.drop_index("ix_session_questions_question", table_name="session_questions")
    op.drop_table("session_questions")
    op.drop_index("ix_attempts_user_submitted", table_name="attempts")
    op.drop_index("ix_attempts_user_question_submitted", table_name="attempts")
    op.drop_index(
        "ix_attempts_unresolved_grading",
        table_name="attempts",
        postgresql_where=sa.text("grading_status IN ('pending', 'grading', 'failed')"),
    )
    op.drop_index("ix_attempts_session", table_name="attempts")
    op.drop_index("ix_attempts_question_version", table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(
        "uq_question_versions_one_published",
        table_name="question_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index(op.f("ix_question_versions_question_id"), table_name="question_versions")
    op.drop_index("ix_question_versions_created_by", table_name="question_versions")
    op.drop_table("question_versions")
    op.drop_index(
        "ix_entitlements_user_active",
        table_name="entitlements",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_entitlements_subscription", table_name="entitlements")
    op.drop_index("ix_entitlements_source_event", table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_index("ix_subscriptions_user", table_name="subscriptions")
    op.drop_index("ix_subscriptions_customer", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_skill_scores_user_score", table_name="skill_scores")
    op.drop_index("ix_skill_scores_category", table_name="skill_scores")
    op.drop_table("skill_scores")
    op.drop_index("ix_sessions_user_started", table_name="sessions", postgresql_using="btree")
    op.drop_index(
        "ix_sessions_user_in_progress",
        table_name="sessions",
        postgresql_where=sa.text("status = 'in_progress'"),
    )
    op.drop_table("sessions")
    op.drop_index(
        "ix_questions_active_selection",
        table_name="questions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("questions")
    op.drop_index("ix_profiles_recruiting_consent", table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("users")
    op.drop_table("categories")
    # ### end Alembic commands ###
